###################### Winlogbeat Configuration Example ########################

winlogbeat.event_logs:
  - name: TGW
    level: warning
    event_id: 100
    ignore_older: 72h

output.logstash:
  # The Logstash hosts
  hosts: ["IP:PORT"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
#  ssl.key: "C:/Windows/Temp/elk/certs/logstash.pkcs8.key"
#  ssl.certificate: "C:/Windows/Temp/elk/certs/logstash.crt"
#  ssl.verification_mode: none
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]



#================================ Logging =====================================

# Sets log level. The default log level is info.
# Available log levels are: error, warning, info, debug
logging.level: info



